WindowManager:
    SummaryScreen
    LogScreen
    GoalsScreen

<SummaryScreen>:
    name: "SummaryScreen"
    on_enter: root.nutrition_comparison()
    BoxLayout:
        id: summary_box_layout
        orientation: 'vertical'
        size: root.width, root.height

        # Greetings Label
        Label:
            id: greetings
            text: "COMPARE TODAY AND GOALS"
            text_size: self.width, None
            font_size: 32
            size_hint_y: 0.1
            height: self.texture_size[1]
            halign: "center"
            valign: "middle"

        Label:
            id: currentDate
            text: app.current_date
            font_Size: 32
            colour: "00FFEE"
            text_size: self.width, None
            font_size: 32
            size_hint_y: 0.1
            height: self.texture_size[1]
            halign: "center"
            valign: "middle"



        
        # ScrollView taking most of the space
        ScrollView:
            id: scroll_view
            size_hint: (1, 0.7)  # Adjusted to 70% of the vertical space
            BoxLayout:
                id: log_layout
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height  

        # "Open Calendar" Button at the bottom of the screen
        Button:
            id: summary_calendar_btn
            text: "Open Calendar"
            size_hint_y: 0.1  # This button takes up 10% of the height
            on_press: root.show_date_picker(self)

        # Bottom BoxLayout for navigating to different screens
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: 0.1  # Take up 10% of the screen height

            Button:
                text: "Go to Goals Screen"
                font_size: 32
                size_hint_x: 0.5  # This button takes 50% of the width
                on_release: 
                    app.root.current = "goalsscreen"
                    root.manager.transition.direction = "right"
            
            Button:
                text: "Go to Log Screen"
                font_size: 32
                size_hint_x: 0.5  # This button takes 50% of the width
                on_release: 
                    app.root.current = "logscreen"
                    root.manager.transition.direction = "left"
    
            
<LogScreen>:
    name: "logscreen"
    GridLayout:
        id: window
        cols: 1
        pos_hint: {"center_x": 0.5, "center_y": 0.5}

        GridLayout:
            id: logo_goals
            cols: 2
            Image:
                source: "logo.png"

        Label:
            id: greeting
            text: "Insert data for this session"
            font_size: 30
            color: "AAAAAA"

        TextInput:
            id: foodname
            multiline: False
            hint_text: "Enter food name"

        TextInput:
            id: cals
            multiline: False
            input_filter: "float"
            hint_text: "Enter calories (kcal)"

        TextInput:
            id: carbs
            multiline: False
            input_filter: "float"
            hint_text: "Enter carbohydrates (g)"

        TextInput:
            id: fats
            multiline: False
            input_filter: "float"
            hint_text: "Enter fats (g)"

        TextInput:
            id: protein
            multiline: False
            input_filter: "float"
            hint_text: "Enter protein (g)"

        #Calendar button and label was here

        Button:
            id: logbutton
            text: "LOG"
            bold: True
            background_color: "00FFCE"
            on_release: 
                root.save_food_log()
                app.root.current = "SummaryScreen"
                root.manager.transition.direction = "right"

        Button:
            text: "Cancel"
            font_size: 32
            on_release: 
                app.root.current = "SummaryScreen"
                root.manager.transition.direction = "right"

<GoalsScreen>:
    name: "goalsscreen"
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        
        Label:
            text: "Set Your Goals"
            font_size: 32

        TextInput:
            id: calorie_goal
            multiline: False
            input_filter: "float"
            hint_text: "Enter calorie goal"

        TextInput:
            id: carb_goal
            multiline: False
            input_filter: "float"
            hint_text: "Enter carbohydrate goal (g)"

        TextInput:
            id: fat_goal
            multiline: False
            input_filter: "float"
            hint_text: "Enter fat goal (g)"

        TextInput:
            id: protein_goal
            multiline: False
            input_filter: "float"
            hint_text: "Enter protein goal (g)"

        Button:
            text: "Save Goals"
            on_press: 
                root.on_save_button_pressed()  # Trigger save action
                app.root.current = "SummaryScreen"
                root.manager.transition.direction = "left"
            font_size: 32

        Button:
            text: "Go to Summary Screen"
            font_size: 32
            on_release: 
                app.root.current = "SummaryScreen"
                root.manager.transition.direction = "left"
