WindowManager:
    SummaryScreen
    LogScreen
    GoalsScreen

<SummaryScreen>:
    name: "SummaryScreen"
    BoxLayout:
        id: summary_box_layout
        orientation: 'vertical'
        size: root.width, root.height
        Label:
            id: greetings
            text: "COMPARE TODAY AND GOALS"
            font_size: 32

        Label:
            id: currentDate
            text: app.current_date
            font_size: 32
            color: "AAAAAA"

        Label:
            text: "Date's total food goes here"
        
        ScrollView:
            id: scroll_view
            size_hint: (1, None)
            size: (400, 300)
            BoxLayout:
                id: log_layout
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height  # Makes the height dynamic


        Button:
            id: summary_calendar_btn
            text: "Open Calendar"
            on_press: root.show_date_picker(self)



        BoxLayout:
            orientation: 'horizontal'
            size: root.width, root.height

            Button:
                text: "Go to Goals Screen"
                font_size: 32
                on_release: 
                    app.root.current = "goalsscreen"
                    root.manager.transition.direction = "right"
            
            Button:
                text: "Go to Log Screen"
                font_size: 32
                on_release: 
                    app.root.current = "logscreen"
                    root.manager.transition.direction = "left"

            
<LogScreen>:
    name: "logscreen"
    GridLayout:
        id: window
        cols: 1
        pos_hint: {"center_x": 0.5, "center_y": 0.5}

        GridLayout:
            id: logo_goals
            cols: 2
            Image:
                source: "logo.png"
            Button:
                id: change_goals"
                text: "Change Goals?"
                font_size: 30
                color: "AAAAAA"
                on_press: 
                    app.root.current = "goalsscreen"
                    root.manager.transition.direction = "right"


        Label:
            id: greeting
            text: "Insert data for this session"
            font_size: 30
            color: "AAAAAA"

        TextInput:
            id: foodname
            multiline: False
            hint_text: "Enter food name"

        TextInput:
            id: cals
            multiline: False
            input_filter: "float"
            hint_text: "Enter calories (kcal)"

        TextInput:
            id: carbs
            multiline: False
            input_filter: "float"
            hint_text: "Enter carbohydrates (g)"

        TextInput:
            id: fats
            multiline: False
            input_filter: "float"
            hint_text: "Enter fats (g)"

        TextInput:
            id: protein
            multiline: False
            input_filter: "float"
            hint_text: "Enter protein (g)"

        #Calendar button and label was here

        Button:
            id: logbutton
            text: "LOG"
            bold: True
            background_color: "00FFCE"
            on_release: 
                root.save_food_log()
                app.root.current = "SummaryScreen"
                root.manager.transition.direction = "right"

        Button:
            text: "Cancel"
            font_size: 32
            on_release: 
                app.root.current = "SummaryScreen"
                root.manager.transition.direction = "right"

<GoalsScreen>:
    name: "goalsscreen"
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        Label:
            text: "Set Your Goals"
            font_size: 32

        Button:
            text: "Go to Summary Screen"
            font_size: 32
            on_release: 
                app.root.current = "SummaryScreen"
                root.manager.transition.direction = "left"
