WindowManager:
    SummaryScreen
    LogScreen
    GoalsScreen

<SummaryScreen>:
    name: "SummaryScreen"
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        Label:
            id: greetings
            text: "This is where you'll compare today and goals"
            font_size: 32

        Button:
            text: "This should work"
            font_size: 32
            on_release: app.change_date(self)

        Button:
            text: "Change TEXT"
            font_size: 32
            on_release: app.change_text(self)  # Fixed method call


        Button:
            text: "Change it BACK"
            font_size: 32
            on_release: app.change_text_two(self)  # Fixed method call



        Button:
            text: "Go to Log Screen"
            font_size: 32
            on_release: 
                app.root.current = "logscreen"
                root.manager.transition.direction = "left"

        Button:
            text: "Go to Goals Screen"
            font_size: 32
            on_release: 
                app.root.current = "goalsscreen"
                root.manager.transition.direction = "right"
             
<LogScreen>:
    name: "logscreen"
    GridLayout:
        id: window
        cols: 1
        pos_hint: {"center_x": 0.5, "center_y": 0.5}

        GridLayout:
            id: logo_goals
            cols: 2
            Image:
                source: "logo.png"
            Button:
                id: change_goals"
                text: "Change Goals?"
                font_size: 30
                color: "AAAAAA"
                on_press: app.root.current = "GoalsScreen"


        Label:
            id: greeting
            text: "Insert data for this session"
            font_size: 30
            color: "AAAAAA"

        TextInput:
            id: foodname
            multiline: False
            hint_text: "Enter food name"

        TextInput:
            id: cals
            multiline: False
            input_filter: "float"
            hint_text: "Enter calories (kcal)"

        TextInput:
            id: carbs
            multiline: False
            input_filter: "float"
            hint_text: "Enter carbohydrates (g)"

        TextInput:
            id: fats
            multiline: False
            input_filter: "float"
            hint_text: "Enter fats (g)"

        TextInput:
            id: protein
            multiline: False
            input_filter: "float"
            hint_text: "Enter protein (g)"

        Button:
            id: calendar_btn
            text: "Open Calendar"
            on_press: root.show_date_picker(self)

        Label:
            id: currentDate
            text: "Today"
            font_size: 25
            color: "AAAAAA"

        Button:
            id: logbutton
            text: "LOG"
            bold: True
            background_color: "00FFCE"
            on_press: root.display_nutrient_tally(self)

        ScrollView:
            id: scroll_view
            size_hint: (1, None)
            size: (400, 300)

            BoxLayout:
                id: log_layout
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                text: log_layout

        Button:
            text: "Go to Summary Screen"
            font_size: 32
            on_release: 
                app.root.current = "SummaryScreen"
                root.manager.transition.direction = "right"

<GoalsScreen>:
    name: "goalsscreen"
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        Label:
            text: "Set Your Goals"
            font_size: 32

        Button:
            text: "Go to Summary Screen"
            font_size: 32
            on_release: 
                app.root.current = "SummaryScreen"
                root.manager.transition.direction = "left"
